#create main app pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoga-api-deployment
  labels:
    app: yoga-api   
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yoga-api
  template:
    metadata:
      labels:
        app: yoga-api
    spec:
      containers:
      - name: yoga-api
        image: proj7acrsep10.azurecr.io/webappyogap5:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  
#########################################################################################################################
#pod to providing network access and network configuration
apiVersion: v1
kind: Service
metadata:
  name: nginx-
spec:
  type: NodePort
  selector:
     app: nginx
  ports:
    port: 80
    nodePort: 30007
